In [0]:
import tensorflow as tf

In [0]:
a = tf.Variable(5)

In [0]:
g = tf.global_variables_initializer()

In [0]:
update = tf.assign(a, a+2)

In [23]:
with tf.Session() as sess:
  
  
  sess.run(g)
  print(sess.run(a))
  for _ in range(3):
        sess.run(update)
        print(sess.run(a))

5
7
9
11


In [24]:
with tf.Session() as sess:
  sess.run(g)
  print(sess.run(a))

5


In [0]:
f = tf.placeholder(tf.float32)

In [0]:
g = f *3

In [27]:
with tf.Session() as sess:
  result = sess.run(g,feed_dict={f:[[1,2,3],[4,5,6],[7,8,9]]})
  print(result)

[[ 3.  6.  9.]
 [12. 15. 18.]
 [21. 24. 27.]]
